language: node_js
node_js:
- '8.0'

script:
  npm test

before_deploy:
  npm run build &&
  cp index.html dist/index.html

#deploy:
#  provider: releases
#  api_key:
#    secure: "${GITHUB_TOKENS}"
#  file_glob: true
#  file: "dist/*"
#  skip_cleanup: true
#  on:
#    tags: true

provider: pages
  skip_cleanup: true
  repo: "qding-bot/demo"
  api_key:
    secure: "${GITHUB_TOKENS}"
  local_dir: dist
  on:
    branch: master