language: node_js
node_js:
 '8.0'

script:
  npm test

before_deploy:
  npm run build &&
  cp index.html dist/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "${GH_TOKEN}"
  keep-history: true
  on:
    branch: master
  local-dir: dist
  repo: "qding-bot/demo"