language: node_js
node_js:
- '8.0'

script:
  npm test

before_deploy:
  npm run build &&
  cp index.html dist/index.html

deploy:
  provider: pages
  skip_cleanup: true
  repo: "qding-bot/demo"
  github-token: "${GH_TOKENS}"
  local_dir: dist
  on:
    branch: master