language: node_js
node_js:
- '8.0'

script:
  npm test

before_deploy:
  cp index.html dist/index.html
  npm run build

deploy:
  provider: releases
  api_key:
    secure: "${GITHUB_TOKENS}"
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true